name: Test

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  test:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7.0.7

      - name: Run tests
        run: go test -v ./...
